# Site settings
title: David's Blog
email: davidromm11@gmail.com
description: >-
  A place for me to share ideas, projects, and acheivments.

baseurl: ''
url: 'https://dcromm.dev'

# Build settings
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Permalink settings - this controls how blog post URLs are generated
permalink: /:year/:month/:day/:title/

# Navigation
nav_links:
  - title: Home
    url: /
  - title: Posts
    url: /blog/
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Author information
author:
  name: David Romm
  email: davidromm11@gmail.com
  bio:
  github: davidromm11
  linkedin: https://www.linkedin.com/in/david-romm/

# Pagination
# paginate_path: '/blog/page:num/'

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/

# SEO settings
social:
  name: David Romm
  links:
    - https://github.com/davidromm11
    - https://www.linkedin.com/in/david-romm/

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Defaults
defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      author: 'David Romm'
  - scope:
      path: ''
    values:
      layout: 'default'

# Footer
footer_links:
  - title: GitHub
    url: https://github.com/davidromm11
  - title: LinkedIn
    url: https://linkedin.com/in/david-romm
    icon: linkedin
